#Build Settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Técnicas para Hackers]
description: [Pequenas Informações relevantes retiradas do livro de Wilson Oliveira
